version: '3'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-radarr:/config
      # - ./movies:/movies #optional
      # - ./downloads-radarr:/downloads #optional
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-sonarr:/config
      # - ./tvseries:/tv #optional
      # - ./downloads-sonarr:/downloads #optional
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - 8686:8686
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-lidarr:/config
      # - ./music:/music #optional
      # - ./downloads-lidarr:/downloads #optional
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  sabnzbd:
    image: lscr.io/linuxserver/sabnzbd:latest
    container_name: sabnzbd
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-sabnzbd:/config
      # - ./downloads-sabnzbd:/downloads #optional
      # - ./downloads-sabnzbd/incomplete:/incomplete-downloads #optional
    ports:
      - 8080:8080
    restart: unless-stopped
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      # TRANSMISSION_WEB_HOME: /transmissionic/ #optional
      # USER: username #optional
      # PASS: password #optional
      # WHITELIST: iplist #optional
      # PEERPORT: peerport #optional
      # HOST_WHITELIST: dnsname list #optional
    volumes:
      - ./config-transmission:/config
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
volumes:
  config-lidarr:
  config-radarr:
  config-sonarr:
  config-prowlarr:
  config-sabnzbd:
  config-transmission:
  # downloads-lidarr:
  # downloads-radarr:
  # downloads-sonarr:
  # downloads-sabnzbd:
  # movies:
  # music:
  # tvseries:
