version: '3'
services:
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    ports:
      - 7878:7878
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-radarr:/config
      # - ./movies:/movies #optional
      # - ./downloads-radarr:/downloads #optional
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    ports:
      - 8989:8989
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-sonarr:/config
      # - ./tvseries:/tv #optional
      # - ./downloads-sonarr:/downloads #optional
  lidarr:
    image: lscr.io/linuxserver/lidarr:latest
    container_name: lidarr
    ports:
      - 8686:8686
    restart: unless-stopped
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-lidarr:/config
      # - ./music:/music #optional
      # - ./downloads-lidarr:/downloads #optional
  prowlarr:
    image: cr.hotio.dev/hotio/prowlarr # lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  # sabnzbd:
  #   image: lscr.io/linuxserver/sabnzbd:latest
  #   container_name: sabnzbd
  #   environment:
  #     PUID: 1000
  #     PGID: 1000
  #     SET_CONTAINER_TIMEZONE: 'true'
  #     CONTAINER_TIMEZONE: America/Santiago
  #     TZ: America/Santiago
  #   volumes:
  #     - ./config-sabnzbd:/config
  #     # - ./downloads-sabnzbd:/downloads #optional
  #     # - ./downloads-sabnzbd/incomplete:/incomplete-downloads #optional
  #   ports:
  #     - 8080:8080
  #   restart: unless-stopped
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-bazarr:/config
    ports:
      - 6767:6767
    restart: unless-stopped
  readarr:
    image: cr.hotio.dev/hotio/readarr
    container_name: readarr
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./config-bazarr:/config
    ports:
      - 8787:8787
    restart: unless-stopped
  mylar3:
    image: lscr.io/linuxserver/mylar3:latest
    container_name: mylar3
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
    volumes:
      - ./mylar3-config:/config
    ports:
      - 8090:8090
    restart: unless-stopped
  unpackerr:
    image: golift/unpackerr
    container_name: unpackerr
    volumes:
      - ./config-unpackerr:/config
    restart: always
    # Get the user:group correct so unpackerr can read and write to your files.
    # user: ${PUID}:${PGID}
    #user: 1000:1000
    # What you see below are defaults for this compose. You only need to modify things specific to your environment.
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      TZ: America/Santiago
      # General config
      UN_DEBUG: 'false'
      UN_LOG_FILE: ''
      UN_LOG_FILES: 10
      UN_LOG_FILE_MB: 10
      UN_INTERVAL: 2m
      UN_START_DELAY: 1m
      UN_RETRY_DELAY: 5m
      UN_MAX_RETRIES: 3
      UN_PARALLEL: 1
      UN_FILE_MODE: 0644
      UN_DIR_MODE: 0755
      # Sonarr Config
      UN_SONARR_0_URL: http://sonarr:8989
      UN_SONARR_0_PATHS_0: /downloads
      UN_SONARR_0_PROTOCOLS: torrent
      UN_SONARR_0_TIMEOUT: 10s
      UN_SONARR_0_DELETE_ORIG: 'false'
      UN_SONARR_0_DELETE_DELAY: 5m
      # Radarr Config
      UN_RADARR_0_URL: http://radarr:7878
      UN_RADARR_0_PATHS_0: /downloads
      UN_RADARR_0_PROTOCOLS: torrent
      UN_RADARR_0_TIMEOUT: 10s
      UN_RADARR_0_DELETE_ORIG: 'false'
      UN_RADARR_0_DELETE_DELAY: 5m
      # Lidarr Config
      UN_LIDARR_0_URL: http://lidarr:8686
      UN_LIDARR_0_PATHS_0: /downloads
      UN_LIDARR_0_PROTOCOLS: torrent
      UN_LIDARR_0_TIMEOUT: 10s
      UN_LIDARR_0_DELETE_ORIG: 'false'
      UN_LIDARR_0_DELETE_DELAY: 5m
      # Readarr Config
      UN_READARR_0_URL: http://readarr:8787
      UN_READARR_0_PATHS_0: /downloads
      UN_READARR_0_PROTOCOLS: torrent
      UN_READARR_0_TIMEOUT: 10s
      UN_READARR_0_DELETE_ORIG: 'false'
      UN_READARR_0_DELETE_DELAY: 5m
      # # Folder Config
      # UN_FOLDER_0_PATH: ''
      # UN_FOLDER_0_EXTRACT_PATH: ''
      # UN_FOLDER_0_DELETE_AFTER: 10m
      # UN_FOLDER_0_DELETE_ORIGINAL: 'false'
      # UN_FOLDER_0_DELETE_FILES: 'false'
      # UN_FOLDER_0_MOVE_BACK: 'false'
      # # Webhook Config
      # UN_WEBHOOK_0_URL: ''
      # UN_WEBHOOK_0_NAME: ''
      # UN_WEBHOOK_0_NICKNAME: Unpackerr
      # UN_WEBHOOK_0_CHANNEL: ''
      # UN_WEBHOOK_0_TIMEOUT: 10s
      # UN_WEBHOOK_0_SILENT: 'false'
      # UN_WEBHOOK_0_IGNORE_SSL: 'false'
      # UN_WEBHOOK_0_EXCLUDE_0: ''
      # UN_WEBHOOK_0_EVENTS_0: 0
      # UN_WEBHOOK_0_TEMPLATE_PATH: '' 
      # UN_WEBHOOK_0_CONTENT_TYPE: application/json
      # # Command Hook Config
      # UN_CMDHOOK_0_COMMAND: ''
      # UN_CMDHOOK_0_NAME: ''
      # UN_CMDHOOK_0_TIMEOUT: 10s
      # UN_CMDHOOK_0_SILENT: 'false'
      # UN_CMDHOOK_0_SHELL: 'false'
      # UN_CMDHOOK_0_EXCLUDE_0: ''
      # UN_CMDHOOK_0_EVENTS_0: 0
    security_opt:
      - no-new-privileges:true
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission
    environment:
      PUID: 1000
      PGID: 1000
      SET_CONTAINER_TIMEZONE: 'true'
      CONTAINER_TIMEZONE: America/Santiago
      # TRANSMISSION_WEB_HOME: /transmissionic/ #optional
      # USER: username #optional
      # PASS: password #optional
      # WHITELIST: iplist #optional
      # PEERPORT: peerport #optional
      # HOST_WHITELIST: dnsname list #optional
    volumes:
      - ./config-transmission:/config
    ports:
      - 19091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
volumes:
  config-lidarr:
  config-radarr:
  config-sonarr:
  config-prowlarr:
  config-bazarr:
  config-readarr:
  config-unpackerr:
  config-mylar3:
  # config-sabnzbd:
  config-transmission:
  # downloads-lidarr:
  # downloads-radarr:
  # downloads-sonarr:
  # downloads-sabnzbd:
  # movies:
  # music:
  # tvseries:
