services:
  radarr:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          # cpus: '0.0001'
          memory: 10M
    volumes:
      - ./YOUR-PATH-FOR-movies:/movies
      - ./YOUR-PATH-FOR-downloads-transmission:/downloads
  sonarr:
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1000M
        reservations:
          # cpus: '0.0001'
          memory: 10M
    volumes:
      - ./YOUR-PATH-FOR-tvseries:/tv
      - ./YOUR-PATH-FOR-downloads-transmission:/downloads
  # lidarr:
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '1'
  #         memory: 1000M
  #       reservations:
  #         # cpus: '0.0001'
  #         memory: 10M
  #   volumes:
  #     - ./YOUR-PATH-FOR-music:/music
  #     - ./YOUR-PATH-FOR-downloads-transmission:/downloads
  bazarr:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          # cpus: '0.0001'
          memory: 10M
    volumes:
      - ./YOUR-PATH-FOR-movies:/movies
      - ./YOUR-PATH-FOR-tvseries:/tv
      - ./YOUR-PATH-FOR-downloads-transmission:/downloads
  # readarr:
  #   deploy:
  #     resources:
  #       limits:
  #         cpus: '0.5'
  #         memory: 512M
  #       reservations:
  #         # cpus: '0.0001'
  #         memory: 10M
  #   volumes:
  #     - ./YOUR-PATH-FOR-books:/books
  #     - ./YOUR-PATH-FOR-downloads-transmission:/downloads
  unpackerr:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          # cpus: '0.0001'
          memory: 10M
    volumes:
      - ./YOUR-PATH-FOR-downloads-transmission:/downloads
    environment:
      UN_SONARR_0_API_KEY: ''
      UN_RADARR_0_API_KEY: ''
      UN_LIDARR_0_API_KEY: ''
      UN_READARR_0_API_KEY: ''
  transmission:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          # cpus: '0.0001'
          memory: 10M
    environment:
      # TRANSMISSION_WEB_HOME: /transmissionic/ #optional
      # USER: username #optional
      # PASS: password #optional
      # WHITELIST: iplist #optional
      # PEERPORT: peerport #optional
      # HOST_WHITELIST: dnsname list #optional
    volumes:
      - ./YOUR-PATH-FOR-downloads-transmission:/downloads
      - ./YOUR-PATH-FOR-torrent-watch-transmission:/watch
  lingarr:
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
        reservations:
          # cpus: '0.0001'
          memory: 10M
    volumes:
      - ./YOUR-PATH-FOR-movies:/movies
      - ./YOUR-PATH-FOR-tvseries:/tv